version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-ant-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
                key: v1-node-modules-{{ checksum "yarn.lock" }}
            - run: yarn
            - run: yarn test:coverage
            - run:
                name: report coverage
                command: |
                  if [[ -z $CI_PULL_REQUEST ]]; then
                    ./node_modules/.bin/codecov
                  fi
            - save_cache:
                key: v1-node-modules-{{ checksum "yarn.lock" }}
                paths:
                - ~/project/node_modules

workflows:
  build-and-test:
    jobs:
      - build-ant-test
